const prefix = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

export const landingAsset = (name: string) =>
  `${prefix}/assets/landing/${name}`;

export const landingAssets = {
  hero: {
    dmitry: `${landingAsset("hero-dmitry.png")}?v=4`,
    arrowButton: landingAsset("hero-arrow-button.svg"),
    glow: `${landingAsset("hero-glow.svg")}?v=5`,
    subtract: `${landingAsset("hero-subtract.svg")}?v=5`,
    mask: landingAsset("hero-mask.svg"),
    swirl: `${landingAsset("hero-swirl.svg")}?v=5`,
    arcShape: `${landingAsset("hero-arc-shape.svg")}?v=4`,
    arcLine: `${landingAsset("hero-arc-line.svg")}?v=4`,
    calendarChip: landingAsset("hero-calendar-chip.svg"),
    promoDecor: landingAsset("promo-decor.svg"),
    signature: landingAsset("hero-signature.svg"),
    /* бордовые иконки дуги (не оранжевые чипы из MyView) */
    iconAwareness: `${landingAsset("icon-direction-awareness.svg")}?v=hero5`,
    iconTechnique: `${landingAsset("icon-direction-technique.svg")}?v=hero5`,
    iconVariability: `${landingAsset("icon-direction-variability.svg")}?v=hero5`,
    iconInteraction: `${landingAsset("icon-direction-interaction.svg")}?v=hero5`,
    iconMusicality: `${landingAsset("icon-direction-musicality.svg")}?v=hero6`,
  },
  icons: {
    eye: landingAsset("icon-eye.svg"),
    bracketBl: landingAsset("icon-bracket-bl.svg"),
    bracketTr: landingAsset("icon-bracket-tr.svg"),
    calendar: landingAsset("icon-calendar.svg"),
    calendarTariff: landingAsset("icon-calendar-tariff.svg"),
    stopwatch: landingAsset("icon-stopwatch.svg"),
    check: `${landingAsset("icon-check-gradient.svg")}?v=2`,
    arrowUp: landingAsset("icon-arrow-up.svg"),
    questionCircle: landingAsset("icon-question-circle-bg.svg"),
    questionMark: landingAsset("icon-question-mark.svg"),
    brainSparkle: landingAsset("icon-brain-sparkle.svg"),
    brainSparkleSm: landingAsset("icon-brain-sparkle-sm.svg"),
    footprint: landingAsset("icon-footprint.svg"),
    shuffle: landingAsset("icon-shuffle.svg"),
    couple: landingAsset("icon-couple.svg"),
    shoe: landingAsset("icon-shoe.svg"),
    shoeProgress: landingAsset("icon-shoe-progress.svg"),
    personSupport: `${landingAsset("icon-person-support.svg")}?v=2`,
    directionAwareness: `${landingAsset("icon-direction-awareness.png")}?v=5`,
    directionTechnique: `${landingAsset("icon-direction-technique.png")}?v=5`,
    directionVariability: `${landingAsset("icon-direction-variability.png")}?v=5`,
    directionInteraction: `${landingAsset("icon-direction-interaction.png")}?v=5`,
    directionMusicality: `${landingAsset("icon-direction-musicality.png")}?v=5`,
    directionsRow: `${landingAsset("chip-directions-row.png")}?v=5`,
    questionChip: landingAsset("chip-question.svg"),
    questionCircleBg: landingAsset("icon-question-circle-bg.svg"),
    calendarGradientChip: `${landingAsset("chip-calendar-gradient.svg")}?v=2`,
    stopwatchChip: landingAsset("chip-stopwatch.png"),
    stopwatchStart: `${landingAsset("icon-stopwatch-start.svg")}?v=2`,
    calendarBoldWhite: `${landingAsset("icon-calendar-bold-white.svg")}?v=2`,
    calendarTariffChip: landingAsset("chip-calendar-tariff.png"),
    stepChips: [
      landingAsset("chip-step-1.png"),
      landingAsset("chip-step-2.png"),
      landingAsset("chip-step-3.png"),
      landingAsset("chip-step-4.png"),
    ],
  },
  photos: {
    dancer: landingAsset("photo-dancer.png"),
    dmitryLearning: landingAsset("photo-dmitry-learning.png"),
    dmitryDirections: landingAsset("dmitry-directions.png"),
    dmitryDirectionsFull: `${landingAsset("dmitry-directions-full.png")}?v=3`,
    liza: landingAsset("photo-liza.png"),
    quoteAvatar: landingAsset("quote-avatar.png"),
    avatarDmitryQuote: `${landingAsset("avatar-dmitry-quote.png")}?v=3`,
    dance: landingAsset("photo-dance.png"),
    danceCutout: `${landingAsset("photo-dance-cutout.png")}?v=1`,
    myView: `${landingAsset("photo-myview.png")}?v=2`,
    lessonsTall: `${landingAsset("photo-lessons.png")}?v=3`,
    telegramTall: `${landingAsset("photo-telegram.png")}?v=2`,
    whatChanges: `${landingAsset("photo-whatchanges.png")}?v=2`,
    videoPreview: landingAsset("video-preview.png"),
  },
  quote: {
    marks: landingAsset("quote-marks.svg"),
  },
  video: {
    playButton: landingAsset("video-play-button.svg"),
  },
  illustrations: {
    awareness3d: landingAsset("illustration-awareness-3d.png"),
    awarenessShadow: landingAsset("illustration-awareness-shadow.svg"),
  },
  backgrounds: {
    directions: landingAsset("bg-directions.jpg"),
    lessons: landingAsset("bg-lessons.jpg"),
    noticed: landingAsset("bg-noticed.png"),
    directionsFull: `${landingAsset("bg-directions-full.png")}?v=2`,
    lessonsFull: `${landingAsset("bg-lessons-full.png")}?v=3`,
  },
  masks: {
    directions: landingAsset("mask-directions.svg"),
    directionsOverlay: landingAsset("mask-directions-overlay.svg"),
    directionsShape: landingAsset("mask-directions-shape.svg"),
    directionsGlow: `${landingAsset("mask-directions-glow.svg")}?v=2`,
  },
  telegram: {
    mockup: landingAsset("mockup-telegram.png"),
  },
  countdown: {
    mockup: `${landingAsset("mockup-countdown.png")}?v=2`,
  },
  lessons: {
    icon01: landingAsset("lesson-icon-01.png"),
    outcomes: landingAsset("illustration-outcomes.png"),
  },
  collage: [
    `${landingAsset("collage-01.png")}?v=3`,
    `${landingAsset("collage-02.png")}?v=3`,
    `${landingAsset("collage-03.png")}?v=3`,
    `${landingAsset("collage-04.png")}?v=3`,
    `${landingAsset("collage-05.png")}?v=3`,
    `${landingAsset("collage-06.png")}?v=3`,
    `${landingAsset("collage-07.png")}?v=3`,
    `${landingAsset("collage-08.png")}?v=3`,
    `${landingAsset("collage-09.png")}?v=3`,
  ],
  reviews: {
    kirillAnna: `${landingAsset("review-kirill-anna.png")}?v=2`,
    yulia: `${landingAsset("review-yulia.png")}?v=2`,
    ekaterina: `${landingAsset("review-ekaterina.png")}?v=2`,
    arrowPrev: `${landingAsset("review-arrow-prev.svg")}?v=2`,
    arrowNext: `${landingAsset("review-arrow-next.svg")}?v=2`,
  },
  social: {
    instagram: landingAsset("social-instagram.svg"),
    telegram: landingAsset("social-telegram.svg"),
    vk: landingAsset("social-vk.svg"),
    facebook: landingAsset("social-facebook.svg"),
    youtube: landingAsset("social-youtube.svg"),
    whatsapp: landingAsset("social-whatsapp.svg"),
    email: landingAsset("social-email.svg"),
  },
  dividers: {
    line: landingAsset("divider-line.svg"),
    tariff: landingAsset("divider-tariff.svg"),
    tariffLine: landingAsset("divider-tariff-line.svg"),
  },
  misc: {
    stepNumberCircle: landingAsset("step-number-circle-bg.svg"),
    questionsSwirl: landingAsset("questions-swirl.svg"),
    arrowScribble: landingAsset("arrow-scribble.svg"),
    routeCurve: landingAsset("route-curve.svg"),
    cursorIcon: landingAsset("cursor-icon.png"),
    stickerGroup: landingAsset("sticker-group.png"),
    lightbulb: `${landingAsset("lightbulb-group.png")}?v=2`,
    hintCursorBg: landingAsset("hint-cursor-bg.svg"),
    lizaSide: landingAsset("illustration-liza-side.png"),
    padlock: `${landingAsset("illustration-padlock.png")}?v=7`,
    videoLessonThumb: `${landingAsset("video-lesson-thumb.png")}?v=3`,
    mockupPayment: `${landingAsset("mockup-payment.png")}?v=2`,
    startBadge: landingAsset("start-badge.svg"),
    telegramInfoIcon: landingAsset("telegram-info-icon.svg"),
  },
  lessonThumbs: [
    landingAsset("lesson-thumb-01.png"),
    landingAsset("lesson-thumb-02.png"),
    landingAsset("lesson-thumb-03.png"),
    landingAsset("lesson-thumb-04.png"),
    landingAsset("lesson-thumb-05.png"),
    landingAsset("lesson-thumb-06.png"),
    landingAsset("lesson-thumb-07.jpg"),
    landingAsset("lesson-thumb-08.png"),
  ],
  direction3d: [
    landingAsset("direction-3d-01.png"),
    landingAsset("direction-3d-02.png"),
    landingAsset("direction-3d-03.png"),
    landingAsset("direction-3d-04.png"),
    landingAsset("direction-3d-05.png"),
  ],
  collageExtra: [
    `${landingAsset("collage-10.png")}?v=3`,
    `${landingAsset("collage-11.png")}?v=3`,
  ],
} as const;
