const prefix = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

/** Cache-bust after WebP optimization pass */
const V = "opt1";

export const landingAsset = (name: string) =>
  `${prefix}/assets/landing/${name}`;

const asset = (name: string, v: string = V) =>
  `${landingAsset(name)}?v=${v}`;

export const landingAssets = {
  hero: {
    dmitry: asset("hero-dmitry.webp"),
    dmitryMobile: asset("hero-dmitry-mobile.webp"),
    arrowButton: landingAsset("hero-arrow-button.svg"),
    glow: asset("hero-glow.svg", "5"),
    subtract: asset("hero-subtract.svg", "5"),
    mask: landingAsset("hero-mask.svg"),
    swirl: asset("hero-swirl.svg", "5"),
    swirlMobile: asset("hero-swirl-mobile.svg", "3"),
    arcShape: asset("hero-arc-shape.svg", "4"),
    arcLine: asset("hero-arc-line.svg", "4"),
    calendarChip: landingAsset("hero-calendar-chip.svg"),
    calendarChipMobile: asset("hero-calendar-chip-mobile.svg", "2"),
    promoDecor: landingAsset("promo-decor.svg"),
    promoGlowMobile: asset("hero-promo-glow-mobile.webp"),
    signature: landingAsset("hero-signature.svg"),
    /* бордовые иконки дуги (не оранжевые чипы из MyView) */
    iconAwareness: asset("icon-direction-awareness.svg", "hero5"),
    iconTechnique: asset("icon-direction-technique.svg", "hero5"),
    iconVariability: asset("icon-direction-variability.svg", "hero5"),
    iconInteraction: asset("icon-direction-interaction.svg", "hero5"),
    iconMusicality: asset("icon-direction-musicality.svg", "hero6"),
  },
  icons: {
    eye: landingAsset("icon-eye.svg"),
    bracketBl: landingAsset("icon-bracket-bl.svg"),
    bracketTr: landingAsset("icon-bracket-tr.svg"),
    calendar: landingAsset("icon-calendar.svg"),
    calendarTariff: landingAsset("icon-calendar-tariff.svg"),
    stopwatch: landingAsset("icon-stopwatch.svg"),
    check: asset("icon-check-gradient.svg", "2"),
    arrowUp: landingAsset("icon-arrow-up.svg"),
    questionCircle: landingAsset("icon-question-circle-bg.svg"),
    questionMark: landingAsset("icon-question-mark.svg"),
    brainSparkle: landingAsset("icon-brain-sparkle.svg"),
    brainSparkleSm: landingAsset("icon-brain-sparkle-sm.svg"),
    footprint: landingAsset("icon-footprint.svg"),
    shuffle: landingAsset("icon-shuffle.svg"),
    couple: landingAsset("icon-couple.svg"),
    shoe: landingAsset("icon-shoe.svg"),
    shoeProgress: landingAsset("icon-shoe-progress.svg"),
    personSupport: asset("icon-person-support.svg", "2"),
    directionAwareness: asset("icon-direction-awareness.webp"),
    directionTechnique: asset("icon-direction-technique.webp"),
    directionVariability: asset("icon-direction-variability.webp"),
    directionInteraction: asset("icon-direction-interaction.webp"),
    directionMusicality: asset("icon-direction-musicality.webp"),
    directionsRow: asset("chip-directions-row.webp"),
    questionChip: landingAsset("chip-question.svg"),
    questionCircleBg: landingAsset("icon-question-circle-bg.svg"),
    calendarGradientChip: asset("chip-calendar-gradient.svg", "2"),
    calendarTelegramMobile: asset("chip-calendar-telegram-mobile.svg", "1"),
    stopwatchChip: landingAsset("icon-stopwatch.svg"),
    stopwatchStart: asset("icon-stopwatch-start.svg", "2"),
    calendarBoldWhite: asset("icon-calendar-bold-white.svg", "2"),
    calendarTariffChip: asset("chip-calendar-tariff.webp"),
    fingerSwipe: asset("icon-finger-swipe.svg", "2"),
    stepChips: [
      asset("chip-step-1.webp"),
      asset("chip-step-2.webp"),
      asset("chip-step-3.webp"),
      asset("chip-step-4.webp"),
    ],
  },
  photos: {
    dancer: asset("photo-dancer.webp"),
    dmitryLearning: asset("photo-dmitry-learning.webp"),
    dmitryDirections: asset("dmitry-directions.webp"),
    dmitryDirectionsFull: asset("dmitry-directions-full.webp"),
    dmitryDirectionsMobile: asset("dmitry-directions-mobile.webp"),
    liza: asset("photo-liza.webp"),
    quoteAvatar: asset("quote-avatar.webp"),
    avatarDmitryQuote: asset("avatar-dmitry-quote.webp"),
    dance: asset("photo-dance.webp"),
    danceCutout: asset("photo-dance-cutout.webp"),
    myView: asset("photo-myview.webp"),
    lessonsTall: asset("photo-lessons.webp"),
    telegramTall: asset("photo-telegram.webp"),
    whatChanges: asset("photo-whatchanges.webp"),
    whatChangesMobile: asset("photo-whatchanges-mobile.webp"),
    videoPreview: asset("video-lesson-thumb.webp"),
  },
  quote: {
    marks: landingAsset("quote-marks.svg"),
  },
  video: {
    playButton: landingAsset("video-play-button.svg"),
    /** Public Supabase Storage URL (set after upload) */
    intro:
      process.env.NEXT_PUBLIC_LANDING_INTRO_VIDEO_URL ??
      "https://api.betango.dance/storage/v1/object/public/landing/explore-tango-1080p.mp4",
  },
  illustrations: {
    awareness3d: asset("illustration-awareness-3d.webp"),
    awarenessShadow: landingAsset("illustration-awareness-shadow.svg"),
  },
  backgrounds: {
    directions: asset("bg-directions.webp"),
    lessons: asset("bg-lessons.webp"),
    noticed: asset("photo-noticed.webp"),
    directionsFull: asset("bg-directions-full.webp"),
    lessonsFull: asset("bg-lessons-full.webp"),
  },
  masks: {
    directions: landingAsset("mask-directions.svg"),
    directionsOverlay: landingAsset("mask-directions-overlay.svg"),
    directionsShape: landingAsset("mask-directions-shape.svg"),
    directionsGlow: asset("mask-directions-glow.svg", "2"),
  },
  telegram: {
    mockup: asset("mockup-telegram.webp"),
  },
  countdown: {
    mockup: asset("mockup-countdown.webp"),
    clockMobile: asset("countdown-clock-mobile.webp"),
  },
  lessons: {
    icon01: asset("lesson-icon-01.webp"),
    outcomes: asset("illustration-outcomes.webp"),
  },
  collage: [
    asset("collage-01.webp"),
    asset("collage-02.webp"),
    asset("collage-03.webp"),
    asset("collage-04.webp"),
    asset("collage-05.webp"),
    asset("collage-06.webp"),
    asset("collage-07.webp"),
    asset("collage-08.webp"),
    asset("collage-09.webp"),
  ],
  reviews: {
    kirillAnna: asset("review-kirill-anna.webp"),
    yulia: asset("review-yulia.webp"),
    ekaterina: asset("review-ekaterina.webp"),
    arrowPrev: asset("review-arrow-prev.svg", "2"),
    arrowNext: asset("review-arrow-next.svg", "2"),
  },
  social: {
    instagram: landingAsset("social-instagram.svg"),
    telegram: landingAsset("social-telegram.svg"),
    vk: landingAsset("social-vk.svg"),
    facebook: landingAsset("social-facebook.svg"),
    youtube: landingAsset("social-youtube.svg"),
    whatsapp: landingAsset("social-whatsapp.svg"),
    email: landingAsset("social-email.svg"),
  },
  dividers: {
    line: landingAsset("divider-line.svg"),
    tariff: landingAsset("divider-tariff.svg"),
    tariffLine: landingAsset("divider-tariff-line.svg"),
  },
  misc: {
    stepNumberCircle: landingAsset("step-number-circle-bg.svg"),
    questionsSwirl: landingAsset("questions-swirl.svg"),
    arrowScribble: landingAsset("arrow-scribble.svg"),
    arrowScribbleMobile: asset("arrow-scribble-mobile.svg", "12"),
    routeCurve: asset("route-curve.svg", "2"),
    routeCurveMobile: asset("route-curve-mobile.svg", "2"),
    cursorIcon: asset("cursor-icon.webp"),
    programStartCouple: asset("program-start-couple.webp"),
    stickerGroup: asset("sticker-group.webp"),
    programStickerMobile: asset("program-sticker-mobile.webp"),
    lightbulb: asset("lightbulb-group.webp"),
    hintCursorBg: landingAsset("hint-cursor-bg.svg"),
    hintCursorBgMobile: asset("hint-cursor-bg.webp"),
    lizaSide: asset("illustration-liza-side.webp"),
    padlock: asset("illustration-padlock.webp"),
    videoLessonThumb: asset("video-lesson-thumb.webp"),
    mockupPayment: asset("mockup-payment.webp"),
    supportQuestionMobile: asset("support-question-mobile.webp"),
    startBadge: landingAsset("start-badge.svg"),
    telegramInfoIcon: landingAsset("telegram-info-icon.svg"),
  },
  lessonThumbs: [
    asset("lesson-thumb-01.webp"),
    asset("lesson-thumb-02.webp"),
    asset("lesson-thumb-03.webp"),
    asset("lesson-thumb-04.webp"),
    asset("lesson-thumb-05.webp"),
    asset("lesson-thumb-06.webp"),
    asset("lesson-thumb-07.webp"),
    asset("lesson-thumb-08.webp"),
  ],
  /** Figma 286:598–646 composed circles (Главная_360); circular alpha */
  programNodesMobile: [
    asset("program-node-01.webp", "circ1"),
    asset("program-node-02.webp", "circ1"),
    asset("program-node-03.webp", "circ1"),
    asset("program-node-04.webp", "circ1"),
    asset("program-node-05.webp", "circ1"),
    asset("program-node-06.webp", "circ1"),
    asset("program-node-07.webp", "circ1"),
    asset("program-node-08.webp", "circ1"),
  ],
  /** Figma 333:411–459 composed circles (2 месяц); circular alpha */
  programNodesMonth2: [
    asset("program-m2-node-01.webp", "circ1"),
    asset("program-m2-node-02.webp", "circ1"),
    asset("program-m2-node-03.webp", "circ1"),
    asset("program-m2-node-04.webp", "circ1"),
    asset("program-m2-node-05.webp", "circ1"),
    asset("program-m2-node-06.webp", "circ1"),
    asset("program-m2-node-07.webp", "circ1"),
    asset("program-m2-node-08.webp", "circ1"),
  ],
  programStickersMonth2: {
    start: asset("program-m2-sticker-start.webp"),
    end: asset("program-m2-sticker-end.webp"),
  },
  /** Figma 385:325–384 composed circles (3 месяц); circular alpha */
  programNodesMonth3: [
    asset("program-m3-node-01.webp", "circ1"),
    asset("program-m3-node-02.webp", "circ1"),
    asset("program-m3-node-03.webp", "circ1"),
    asset("program-m3-node-04.webp", "circ1"),
    asset("program-m3-node-05.webp", "circ1"),
    asset("program-m3-node-06.webp", "circ1"),
    asset("program-m3-node-07.webp", "circ1"),
    asset("program-m3-node-08.webp", "circ1"),
  ],
  /** Couple + 3 filled bars (month 3) */
  programStickerMonth3: asset("program-m3-sticker.webp"),
  direction3d: [
    asset("direction-3d-01.webp"),
    asset("direction-3d-02.webp"),
    asset("direction-3d-03.webp"),
    asset("direction-3d-04.webp"),
    asset("direction-3d-05.webp"),
  ],
  /** Composed Figma frames 325:26+ (clipped + correct orientation) */
  direction3dMobile: [
    asset("direction-3d-mobile-01.webp"),
    asset("direction-3d-mobile-02.webp"),
    asset("direction-3d-mobile-03.webp"),
    asset("direction-3d-mobile-04.webp"),
    asset("direction-3d-mobile-05.webp"),
  ],
  collageExtra: [
    asset("collage-10.webp"),
    asset("collage-11.webp"),
  ],
  /** Главная_360 reviews collage */
  collageMobile: {
    image37: asset("collage-m-37.webp"),
    image35: asset("collage-m-35.webp"),
    image36: asset("collage-m-36.webp"),
    image39: asset("collage-m-39.webp"),
    image41: asset("collage-m-41.webp"),
  },
} as const;
