const prefix = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

export const landingAsset = (name: string) =>
  `${prefix}/assets/landing/${name}`;

export const landingAssets = {
  hero: {
    dmitry: landingAsset("hero-dmitry.png"),
    arrowButton: landingAsset("hero-arrow-button.svg"),
    glow: landingAsset("hero-glow.svg"),
    mask: landingAsset("hero-mask.svg"),
    swirl: landingAsset("hero-swirl.svg"),
    arcShape: landingAsset("hero-arc-shape.svg"),
    arcLine: landingAsset("hero-arc-line.svg"),
    calendarChip: landingAsset("hero-calendar-chip.svg"),
    promoDecor: landingAsset("promo-decor.svg"),
    signature: landingAsset("hero-signature.svg"),
  },
  icons: {
    eye: landingAsset("icon-eye.svg"),
    bracketBl: landingAsset("icon-bracket-bl.svg"),
    bracketTr: landingAsset("icon-bracket-tr.svg"),
    calendar: landingAsset("icon-calendar.svg"),
    calendarTariff: landingAsset("icon-calendar-tariff.svg"),
    stopwatch: landingAsset("icon-stopwatch.svg"),
    check: landingAsset("icon-check-gradient.svg"),
    arrowUp: landingAsset("icon-arrow-up.svg"),
    questionCircle: landingAsset("icon-question-circle-bg.svg"),
    questionMark: landingAsset("icon-question-mark.svg"),
    brainSparkle: landingAsset("icon-brain-sparkle.svg"),
    brainSparkleSm: landingAsset("icon-brain-sparkle-sm.svg"),
    footprint: landingAsset("icon-footprint.svg"),
    shuffle: landingAsset("icon-shuffle.svg"),
    couple: landingAsset("icon-couple.svg"),
    shoe: landingAsset("icon-shoe.svg"),
    shoeProgress: landingAsset("icon-shoe-progress.svg"),
    directionAwareness: landingAsset("icon-direction-awareness.svg"),
    directionTechnique: landingAsset("icon-direction-technique.svg"),
    directionMusicality: landingAsset("icon-direction-musicality.svg"),
    directionInteraction: landingAsset("icon-direction-interaction.svg"),
    directionVariability: landingAsset("icon-direction-variability.svg"),
  },
  photos: {
    dancer: landingAsset("photo-dancer.png"),
    dmitryLearning: landingAsset("photo-dmitry-learning.png"),
    dmitryDirections: landingAsset("dmitry-directions.png"),
    dmitryDirectionsFull: landingAsset("dmitry-directions-full.png"),
    liza: landingAsset("photo-liza.png"),
    quoteAvatar: landingAsset("quote-avatar.png"),
    avatarDmitryQuote: landingAsset("avatar-dmitry-quote.png"),
    dance: landingAsset("photo-dance.png"),
    myView: landingAsset("photo-myview.png"),
    lessonsTall: landingAsset("photo-lessons.png"),
    telegramTall: landingAsset("photo-telegram.png"),
    whatChanges: landingAsset("photo-whatchanges.png"),
    videoPreview: landingAsset("video-preview.png"),
  },
  quote: {
    marks: landingAsset("quote-marks.svg"),
  },
  video: {
    playButton: landingAsset("video-play-button.svg"),
  },
  illustrations: {
    awareness3d: landingAsset("illustration-awareness-3d.png"),
    awarenessShadow: landingAsset("illustration-awareness-shadow.svg"),
  },
  backgrounds: {
    directions: landingAsset("bg-directions.jpg"),
    lessons: landingAsset("bg-lessons.jpg"),
    noticed: landingAsset("bg-noticed.png"),
    directionsFull: landingAsset("bg-directions-full.png"),
    lessonsFull: landingAsset("bg-lessons-full.png"),
  },
  masks: {
    directions: landingAsset("mask-directions.svg"),
    directionsOverlay: landingAsset("mask-directions-overlay.svg"),
    directionsShape: landingAsset("mask-directions-shape.svg"),
    directionsGlow: landingAsset("mask-directions-glow.svg"),
  },
  telegram: {
    mockup: landingAsset("mockup-telegram.png"),
  },
  countdown: {
    mockup: landingAsset("mockup-countdown.png"),
  },
  lessons: {
    icon01: landingAsset("lesson-icon-01.png"),
    outcomes: landingAsset("illustration-outcomes.png"),
  },
  collage: [
    landingAsset("collage-01.png"),
    landingAsset("collage-02.png"),
    landingAsset("collage-03.png"),
    landingAsset("collage-04.png"),
    landingAsset("collage-05.png"),
    landingAsset("collage-06.png"),
    landingAsset("collage-07.png"),
    landingAsset("collage-08.png"),
    landingAsset("collage-09.png"),
  ],
  reviews: {
    kirillAnna: landingAsset("review-kirill-anna.png"),
    yulia: landingAsset("review-yulia.png"),
    ekaterina: landingAsset("review-ekaterina.png"),
  },
  social: {
    instagram: landingAsset("social-instagram.svg"),
    telegram: landingAsset("social-telegram.svg"),
    vk: landingAsset("social-vk.svg"),
    facebook: landingAsset("social-facebook.svg"),
    youtube: landingAsset("social-youtube.svg"),
    whatsapp: landingAsset("social-whatsapp.svg"),
    email: landingAsset("social-email.svg"),
  },
  dividers: {
    line: landingAsset("divider-line.svg"),
    tariff: landingAsset("divider-tariff.svg"),
    tariffLine: landingAsset("divider-tariff-line.svg"),
  },
  misc: {
    stepNumberCircle: landingAsset("step-number-circle-bg.svg"),
    questionsSwirl: landingAsset("questions-swirl.svg"),
    arrowScribble: landingAsset("arrow-scribble.svg"),
    routeCurve: landingAsset("route-curve.svg"),
    cursorIcon: landingAsset("cursor-icon.png"),
    stickerGroup: landingAsset("sticker-group.png"),
    lightbulb: landingAsset("lightbulb-group.png"),
    hintCursorBg: landingAsset("hint-cursor-bg.svg"),
    lizaSide: landingAsset("illustration-liza-side.png"),
    videoLessonThumb: landingAsset("video-lesson-thumb.png"),
    mockupPayment: landingAsset("mockup-payment.png"),
    startBadge: landingAsset("start-badge.svg"),
    telegramInfoIcon: landingAsset("telegram-info-icon.svg"),
  },
  lessonThumbs: [
    landingAsset("lesson-thumb-01.png"),
    landingAsset("lesson-thumb-02.png"),
    landingAsset("lesson-thumb-03.png"),
    landingAsset("lesson-thumb-04.png"),
    landingAsset("lesson-thumb-05.png"),
    landingAsset("lesson-thumb-06.png"),
    landingAsset("lesson-thumb-07.jpg"),
    landingAsset("lesson-thumb-08.png"),
  ],
  direction3d: [
    landingAsset("direction-3d-01.png"),
    landingAsset("direction-3d-02.png"),
    landingAsset("direction-3d-03.png"),
    landingAsset("direction-3d-04.png"),
    landingAsset("direction-3d-05.png"),
  ],
  collageExtra: [
    landingAsset("collage-10.png"),
    landingAsset("collage-11.png"),
  ],
} as const;
