import type { Locale } from "@/lib/catalog/types";

const ru = {
  materialsTitle: "Мои материалы",
  backToMaterials: "Вернуться к материалам",
  open: "Открыть",
  renew: "Продлить доступ",
  expired: "Доступ закончился",
  remainingDays: "Осталось: {left} из {total} {unit}",
  remainingHours: "Осталось: {hours} {unit} из {total} {dayUnit}",
  catalogCta: "Перейти в каталог",
  emptyTitle: "Пока нет купленных материалов",
  emptyBody:
    "После оплаты уроки и курсы появятся здесь. Выберите видео в каталоге и оформите заказ.",
  errorTitle: "Не получилось загрузить материалы",
  errorBody: "Проверьте соединение и попробуйте ещё раз.",
  retry: "Повторить",
  navMaterials: "Мои материалы",
  navProfile: "Настройки профиля",
  navOrders: "История покупок",
  navSupport: "Написать в поддержку",
  logout: "Выйти",
  programTitle: "Программа курса",
  programEmpty: "Программа курса появится здесь, когда её добавят к этому материалу.",
  watchDescriptionFallback: "",
  playerNote: "Плеер Kinescope появится в этом окне.",
  profileTitle: "Настройки профиля",
  securityTitle: "Параметры безопасности",
  loginLabel: "Логин",
  newPassword: "Новый пароль",
  confirmPassword: "Подтвердить новый пароль",
  save: "Сохранить",
  saving: "Сохранение…",
  passwordSaved: "Пароль обновлён",
  passwordMismatch: "Введённые пароли не совпадают",
  weakPassword: "Пароль слишком короткий. Придумайте более надёжный.",
  passwordError: "Не получилось сохранить пароль. Попробуйте ещё раз.",
  logoutError: "Не получилось выйти. Попробуйте ещё раз.",
  ordersTitle: "История покупок",
  ordersEmptyTitle: "Покупок пока нет",
  ordersEmptyBody:
    "Оплаченные заказы появятся здесь. Выберите материалы в каталоге и оформите заказ.",
  ordersErrorTitle: "Не получилось загрузить историю",
  orderPaid: "Оплачен",
  expiredTitle: "Доступ закончился",
  expiredBody:
    "Срок доступа к материалу истёк. Здесь будет предложение открыть приложение и получить бонус — QR и ссылки на сторы появятся, когда их утвердят.",
  expiredSlotLabel: "QR и ссылки на сторы",
  expiredBack: "К моим материалам",
  dayOne: "дня",
  dayFew: "дней",
  dayMany: "дней",
  hourOne: "час",
  hourFew: "часа",
  hourMany: "часов",
} as const;

const en = {
  materialsTitle: "My materials",
  backToMaterials: "Back to materials",
  open: "Open",
  renew: "Renew access",
  expired: "Access ended",
  remainingDays: "Remaining: {left} of {total} {unit}",
  remainingHours: "Remaining: {hours} {unit} of {total} {dayUnit}",
  catalogCta: "Go to catalog",
  emptyTitle: "No purchased materials yet",
  emptyBody:
    "After payment, lessons and courses will appear here. Choose videos in the catalog and place an order.",
  errorTitle: "Couldn’t load materials",
  errorBody: "Check your connection and try again.",
  retry: "Try again",
  navMaterials: "My materials",
  navProfile: "Profile settings",
  navOrders: "Order history",
  navSupport: "Write to support",
  logout: "Sign out",
  programTitle: "Course program",
  programEmpty: "The course program will appear here when it is added to this material.",
  watchDescriptionFallback: "",
  playerNote: "The Kinescope player will appear in this window.",
  profileTitle: "Profile settings",
  securityTitle: "Security",
  loginLabel: "Login",
  newPassword: "New password",
  confirmPassword: "Confirm new password",
  save: "Save",
  saving: "Saving…",
  passwordSaved: "Password updated",
  passwordMismatch: "The passwords do not match",
  weakPassword: "The password is too short. Please choose a stronger one.",
  passwordError: "Couldn’t save the password. Please try again.",
  logoutError: "Couldn’t sign out. Please try again.",
  ordersTitle: "Order history",
  ordersEmptyTitle: "No orders yet",
  ordersEmptyBody:
    "Paid orders will appear here. Choose materials in the catalog and place an order.",
  ordersErrorTitle: "Couldn’t load order history",
  orderPaid: "Paid",
  expiredTitle: "Access ended",
  expiredBody:
    "Access to this material has expired. An offer to open the app and receive a bonus will appear here — QR and store links land once they are approved.",
  expiredSlotLabel: "QR and store links",
  expiredBack: "Back to my materials",
  dayOne: "day",
  dayFew: "days",
  dayMany: "days",
  hourOne: "hour",
  hourFew: "hours",
  hourMany: "hours",
} as const;

export type AccountCopy = { [K in keyof typeof ru]: string };

export const accountCopy = ru;

export function accountT(locale: Locale = "ru"): AccountCopy {
  return locale === "en" ? en : ru;
}
